/* Modelagem Basica*/

CLIENTE

NOME - CARACTER (30) 
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

MODELAGEM CONCEITUAL -
MODELAGEM LOGICA
MODELAGEM FISICA

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTE(
   NOME VARCHAR(30),
   SEXO CHAR(1),
   EMAIL VARCHAR(30),
   CPF INT(11),
   TELEFONE VARCHAR(30),
   ENDERECO VARCHAR(100)

);

SHOW TABLES;

DESC CLIENTE;

INSERT INTO CLIENTE VALUES ('CLIENTE TESTE 01', 'M', 'cliente01@example.com', 100000001, '00000001', 'ENDERECO FICTICIO 01 - CIDADE EXEMPLO - EX');

INSERT INTO CLIENTE VALUES ('CLIENTE TESTE 02', 'F', 'cliente02@example.com', 100000002, '00000002', 'ENDERECO FICTICIO 02 - CIDADE EXEMPLO - EX');

INSERT INTO CLIENTE VALUES('CLIENTE TESTE 03', 'M', NULL, 100000003, '00000003', 'ENDERECO FICTICIO 03 - CIDADE EXEMPLO - EX');

/* COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE (NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLIENTE TESTE 04', 'F', 'ENDERECO FICTICIO 04 - CIDADE EXEMPLO - EX', '00000004', 100000004);



SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

SELECT *FROM CLIENTE;

SELECT NOW() AS DATA_HORA, 'ALUNO EXEMPLO' AS aluno;
